# -*- coding: utf-8 -*-
"""Лабораторная работа 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vrkPqbQv70XgevYp7CZhzeyfiI4-Vkgt
"""

while True:
  p1 = input('Введите пароль:')
  p2 = input('Подтвердите пароль:')

  if len(p1) < 8:
    print('Пароль слишком короткий')
    continue
  if "123" in p1:
    print('Пароль слишком простой')
    continue
  if p1 != p2:
    print('Различаются')
    continue
  print('ОК')
  break

letter_A= '''
  ***
 *   *
 *   *
 *****
 *   *
 *   *
 *   *
'''

print(letter_A)

def encrypt(text):
    encrypted_text = ""
    for char in text:
        if char.isalpha():
            if char.lower() == 'a':
                encrypted_text += 'y'
            elif char.lower() == 'b':
                encrypted_text += 'z'
            else:
                encrypted_char = chr(ord(char) - 2)
                encrypted_text += encrypted_char
        else:
            encrypted_text += char
    return encrypted_text


plaintext = input("Введите текст для шифрования: ")
encrypted_text = encrypt(plaintext)
print("Зашифрованный текст:", encrypted_text)

def reverse_words(text):
    words = text.split()
    reversed_text = ' '.join(reversed(words))
    return reversed_text


input_text = input("Введите текст: ")
new_text = reverse_words(input_text)
print("Новый текст с обратным порядком слов:", new_text)

def swap_characters(text):
    swapped_text = ''
    for i in range(0, len(text), 2):

        if i == len(text) - 1:
            swapped_text += text[i]
        else:

            swapped_text += text[i + 1]
            swapped_text += text[i]
    return swapped_text

input_text = input("Введите текст: ")
new_text = swap_characters(input_text)
print("Новая строка с символами, поменянными местами через один:", new_text)

def count_spaces(text):
    space_count = text.count(' ')
    return space_count

input_text = input("Введите строку: ")
spaces = count_spaces(input_text)
print("Количество пробелов в строке:", spaces)

def find_letters(text):

    if 'и' in text and 'к' in text:
        return True
    else:
        return False


input_text = input("Введите строку: ")
if find_letters(input_text):
    print("Буквы 'и' и 'к' есть в строке.")
else:
    print("Таких букв нет.")

string = 'пишите код так, как будто сопровождать его будет склонный к насилию психопат, который знает, где вы живете'

string = string.capitalize()

index = string.find('сопровождать')

string = string.replace('сопровождать', 'поддерживать')

parts = string.split(',')


new_string = ','.join(parts)

print("Строка с заглавной буквы:", new_string)
print("Индекс вхождения 'сопровождать':", index)
print("Измененная строка:", string)

string = 'Сидел барсук в своей норе и ел картошечку пюре'


length = len(string)


string += '.'

substring = 'ре' in string


count_re = string.count('ре')

penultimate_char = string[-2]


odd_indices_chars = string[1::2]

words_count = len(string.split())


print("Длина строки:", length)
print("Строка после операции сложения со строкой '.' :", string)
print("Подстрока 'ре' входит в строку:", substring)
print("Количество вхождений подстроки 'ре':", count_re)
print("Предпоследний символ строки:", penultimate_char)
print("Символы с нечетными индексами:", odd_indices_chars)
print("Количество слов в строке:", words_count)